require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShoppingListsController do

  # This should return the minimal set of attributes required to create a valid
  # ShoppingList. As you add validations to ShoppingList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShoppingListsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all shopping_lists as @shopping_lists" do
      shopping_list = ShoppingList.create! valid_attributes
      get :index, {}, valid_session
      assigns(:shopping_lists).should eq([shopping_list])
    end
  end

  describe "GET show" do
    it "assigns the requested shopping_list as @shopping_list" do
      shopping_list = ShoppingList.create! valid_attributes
      get :show, {:id => shopping_list.to_param}, valid_session
      assigns(:shopping_list).should eq(shopping_list)
    end
  end

  describe "GET new" do
    it "assigns a new shopping_list as @shopping_list" do
      get :new, {}, valid_session
      assigns(:shopping_list).should be_a_new(ShoppingList)
    end
  end

  describe "GET edit" do
    it "assigns the requested shopping_list as @shopping_list" do
      shopping_list = ShoppingList.create! valid_attributes
      get :edit, {:id => shopping_list.to_param}, valid_session
      assigns(:shopping_list).should eq(shopping_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ShoppingList" do
        expect {
          post :create, {:shopping_list => valid_attributes}, valid_session
        }.to change(ShoppingList, :count).by(1)
      end

      it "assigns a newly created shopping_list as @shopping_list" do
        post :create, {:shopping_list => valid_attributes}, valid_session
        assigns(:shopping_list).should be_a(ShoppingList)
        assigns(:shopping_list).should be_persisted
      end

      it "redirects to the created shopping_list" do
        post :create, {:shopping_list => valid_attributes}, valid_session
        response.should redirect_to(ShoppingList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shopping_list as @shopping_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShoppingList.any_instance.stub(:save).and_return(false)
        post :create, {:shopping_list => { "title" => "invalid value" }}, valid_session
        assigns(:shopping_list).should be_a_new(ShoppingList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShoppingList.any_instance.stub(:save).and_return(false)
        post :create, {:shopping_list => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shopping_list" do
        shopping_list = ShoppingList.create! valid_attributes
        # Assuming there are no other shopping_lists in the database, this
        # specifies that the ShoppingList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ShoppingList.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => shopping_list.to_param, :shopping_list => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested shopping_list as @shopping_list" do
        shopping_list = ShoppingList.create! valid_attributes
        put :update, {:id => shopping_list.to_param, :shopping_list => valid_attributes}, valid_session
        assigns(:shopping_list).should eq(shopping_list)
      end

      it "redirects to the shopping_list" do
        shopping_list = ShoppingList.create! valid_attributes
        put :update, {:id => shopping_list.to_param, :shopping_list => valid_attributes}, valid_session
        response.should redirect_to(shopping_list)
      end
    end

    describe "with invalid params" do
      it "assigns the shopping_list as @shopping_list" do
        shopping_list = ShoppingList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShoppingList.any_instance.stub(:save).and_return(false)
        put :update, {:id => shopping_list.to_param, :shopping_list => { "title" => "invalid value" }}, valid_session
        assigns(:shopping_list).should eq(shopping_list)
      end

      it "re-renders the 'edit' template" do
        shopping_list = ShoppingList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShoppingList.any_instance.stub(:save).and_return(false)
        put :update, {:id => shopping_list.to_param, :shopping_list => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shopping_list" do
      shopping_list = ShoppingList.create! valid_attributes
      expect {
        delete :destroy, {:id => shopping_list.to_param}, valid_session
      }.to change(ShoppingList, :count).by(-1)
    end

    it "redirects to the shopping_lists list" do
      shopping_list = ShoppingList.create! valid_attributes
      delete :destroy, {:id => shopping_list.to_param}, valid_session
      response.should redirect_to(shopping_lists_url)
    end
  end

end
